### PR TITLE
Fix: DO-1902 fix default pandas.Timestamp encoder & build 1.2.2

### PR DESCRIPTION
**Pull request by krzysztof-causalens**
## Motivation and Context

Issue found when testing out new 1.2 changes, the default encoder for pandas.Timestamp was previously outputting a datetime object which was unserializable. Fixed by using the same isoformat method as the native datetime object uses.

## How Has This Been Tested?

Tested by modifying code directly in the project where the issue was spotted

## PR Checklist:

- [x] I have implemented all requirements? (see JIRA, project documentation).
- [x] I am not affecting someone else's work, If I am, they are included as a reviewer.
- [x] I have added relevant tests (unit, integration or regression).
- [x] I have added comments to all the bits that are hard to follow.
- [x] I have added/updated Documentation.
- [x] I have updated the appropriate changelog with a line for my changes.

### CODE REVIEW

**Review by tamara-causalens — APPROVED** [review]

**Review by patricia-causalens — APPROVED** [review]
Good find, how did this came up out of curiosity

**Comment by krzysztof-causalens** [comment]
Added a test for all the types, fixed some other issues uncovered in the process. @tamara-causalens could you have a look if the serialization for the pandas/numpy types makes sense? For few which I couldn't figure out a generic way to deserialize I just default to raising NotImplementedError, deserialization handler only comes into play when user annotates their function with that type so in those cases they can just not annotate it and parse it themselves.

**Comment by claudiawestby** [comment]
> Good find, how did this came up out of curiosity

testing out some hlcs I had a `DerivedVariable` that was of type `List[ScenarioResult]` and I noticed that it could no longer be deserialized

**Comment by claudiawestby** [comment]
thanks for debugging this!

**Review by tamara-causalens — APPROVED** [review]

**Pull request merged**
