### PR TITLE
Improvement: DO-3640: Input and NumericInput now accept standard HTML element props

### PR DESCRIPTION
**Pull request by Roman-Kornev**
## Motivation and Context

Previously, `Input` and `NumericInput` did not accept standard HTML props as it doesn't extend from the `InputHTMLAttributes<HTMLInputElement>` interface. Now they both do, so we can remove the redundant props being passed and use all standard html props without issues.

## How Has This Been Tested?

Locally

## PR Checklist:

- [x] I have implemented all requirements? (see JIRA, project documentation).
- [x] I am not affecting someone else's work, If I am, they are included as a reviewer.
- [x] I have added relevant tests (unit, integration or regression).
- [x] I have added comments to all the bits that are hard to follow.
- [x] I have added/updated Documentation.
- [x] I have updated the appropriate changelog with a line for my changes.

### CODE REVIEW

**Review by krzysztof-causalens — APPROVED** [review]
Nice, LGTM

**Review by patricia-causalens — APPROVED** [review]
LGTM, thanks for fixing this!

**Review by tamara-causalens — APPROVED** [review]
Great find!

**Comment by tamara-causalens** [comment]
lovely! good to merge @Roman-Kornev?

**Comment by Roman-Kornev** [comment]
@tamara-causalens Yeah, should be good

**Pull request merged**
