### PR TITLE
Fix: DO-4169 Add icon display to dropdown items

### PR DESCRIPTION
**Pull request by sam-causalens**
## Motivation and Context
* Add the display of icons to dropdown list items (see screenshot below)

## Implementation Description
Display the icon at the end of the row if it's present, expects any JSX element.

## Any new dependencies Introduced
No

## How Has This Been Tested?
Locally in storybook

## PR Checklist:

- [x] I have implemented all requirements? (see JIRA, project documentation).
- [x] I am not affecting someone else's work, If I am, they are included as a reviewer.
- [ ] I have added relevant tests (unit, integration or regression).
- [ ] I have added comments to all the bits that are hard to follow.
- [ ] I have added/updated Documentation.
- [ ] I have updated the appropriate changelog with a line for my changes.

## Screenshots (if appropriate):
Screenshot 2024-11-22 at 15 30 00

### CODE REVIEW

**Review by krzysztof-causalens — APPROVED** [review]

**Comment by krzysztof-causalens** [comment]
@sam-causalens out of curiosity, what happens if an icon is added to an item which would overflow? e.g. in your screen shot, what if the second-to-last item had an icon attached? would the icon be pushed out of view?

**Comment by sam-causalens** [comment]
> @sam-causalens out of curiosity, what happens if an icon is added to an item which would overflow? e.g. in your screen shot, what if the second-to-last item had an icon attached? would the icon be pushed out of view?

Good point, I'll check.

**Comment by sam-causalens** [comment]
> @sam-causalens out of curiosity, what happens if an icon is added to an item which would overflow? e.g. in your screen shot, what if the second-to-last item had an icon attached? would the icon be pushed out of view?

@krzysztof-causalens You were correct, I'd broken the truncation. This is fixed for both icon items and non icon items (see updated screenshot)

**Comment by krzysztof-causalens** [comment]
> > @sam-causalens out of curiosity, what happens if an icon is added to an item which would overflow? e.g. in your screen shot, what if the second-to-last item had an icon attached? would the icon be pushed out of view?
> 
> @krzysztof-causalens You were correct, I'd broken the truncation. This is fixed for both icon items and non icon items (see updated screenshot)

Looks good, thanks for fixing that.

**Pull request merged**
