### PR TITLE
Fix: DO-4367 Loosen Jinja2 dep constraint

### PR DESCRIPTION
**Pull request by sam-causalens**
## Motivation and Context
* Other libs in our ecosystem (or ecosystem we wish to install into) have new versions that requireme jinja2 being > 3.1 so extend dara to allow it as it barely uses jinja and the api still works as before for what we do.

## Implementation Description
* Allow 3.1.x versions of Jinja2

## Any new dependencies Introduced
No

## How Has This Been Tested?
Existing unit tests should catch any issues

## PR Checklist:

- [x] I have implemented all requirements? (see JIRA, project documentation).
- [x] I am not affecting someone else's work, If I am, they are included as a reviewer.
- [ ] I have added relevant tests (unit, integration or regression).
- [ ] I have added comments to all the bits that are hard to follow.
- [ ] I have added/updated Documentation.
- [x] I have updated the appropriate changelog with a line for my changes.

### CODE REVIEW

**Review by krzysztof-causalens — COMMENTED** [review]
Have you tested this with an app? AFAIK the issue here is that `fastapi-vite` uses `Jinja` under the hood and they were using some API which was removed in some minor version. This isn't covered by unit tests, but if you've checked that everything works fine then LGTM.

**Comment by sam-causalens** [comment]
> Have you tested this with an app? AFAIK the issue here is that `fastapi-vite` uses `Jinja` under the hood and they were using some API which was removed in some minor version. This isn't covered by unit tests, but if you've checked that everything works fine then LGTM.

Yeah, that seems to be the issue. I'll work on it tomorrow to try and resolve.

**Comment by krzysztof-causalens** [comment]
> > Have you tested this with an app? AFAIK the issue here is that `fastapi-vite` uses `Jinja` under the hood and they were using some API which was removed in some minor version. This isn't covered by unit tests, but if you've checked that everything works fine then LGTM.
> 
> Yeah, that seems to be the issue. I'll work on it tomorrow to try and resolve.

FYI we've investigated this in the past, the solution is to fork it since the library is basically unmaintained (outside of their move to Pydantic v2). We had it planned, just never got around to it - should be fairly simple, it's a small library, just needs creating a repo, fixing the issue and publishing to PyPI.

**Review by krzysztof-causalens — APPROVED** [review]
LGTM if it works correctly with the fork, thanks

**Comment by sam-causalens** [comment]
> LGTM if it works correctly with the fork, thanks

Yep looks to work well. I span up a local app to test and that worked too 👍

**Pull request merged**
